services:
  - type: web
    name: chat-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: daphne -b 0.0.0.0 -p $PORT chat_config.asgi:application
    envVars:
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: chat-cache
          property: connectionString
