services:
  - type: web
    name: chat-application
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn chat_project.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mychat-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        value: false

databases:
  - name: mychat-db
    databaseName: railway
    user: root
